name: pulse
description: Weather app for the Linux Desktop.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  animated_emoji: ^3.1.0
  collection: ^1.19.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: ^9.2.4
  flutter_weather_bg_null_safety:
    git:
      url: https://github.com/Feichtmeier/flutter_weather_bg_null_safety
      ref: 657a3107993c32d9aa85b272b2991440f3081f3a       

  handy_window: ^0.4.0
  http: ^1.3.0
  intl: ^0.19.0
  open_weather_client: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  safe_change_notifier: ^0.4.0
  shared_preferences: ^2.5.1
  watch_it: ^1.6.2
  xdg_directories: ^1.0.4
  yaru: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/pulse.png"
  macos:
    generate: true
    image_path: "assets/pulse.png"
 

dependency_overrides:
  intl: 0.19.0